### PR TITLE
Remove Airflow version check for accessing {{dag_run.note}}

### LINKED ISSUE #73: Check if "note" field exists on dag_run without examining versions
Figure out a way to determine whether it is safe to access `{{dag_run.note}}` _without_ examining versions.  The code is brittle; prefer to examine _whether_ we have a note on `TaskInstance` and then include it.

_Originally posted by @arielshaqed in https://github.com/treeverse/airflow-provider-lakeFS/issues/71#issuecomment-1668433267_

### PR DESCRIPTION
**Pull request by arielshaqed**
Fixes #73.

### CODE REVIEW

**Review by Jonathan-Rosenberg — APPROVED** [review]
Cool

**Comment by FredrikBakken** [comment]
Great! I'm a bit booked today and tomorrow, but I'll have a closer look at this on Friday to fully review it :smile:

**Comment by FredrikBakken** [comment]
Everything works as expected with these changes - tested on Apache Airflow versions `2.4.3` and `2.6.3`.

LGTM 🚀

**Comment by arielshaqed** [comment]
Thanks!

Pulling & releasing a patch version.

**Pull request merged**
