### PR TITLE
feat: add branch delete operator

### LINKED ISSUE #53: [FeatureRequest] delete branch airflow operator without lakeCTL installation
For scenarios such as staging testing environment with airflow there is a need for delete operator.

Chain of operations example:

**# SETUP**
 create_s3_bucket, -> create lakefs branch
create_lakefs_branch,
**# BODY**
emr_serverless_app,
wait_for_app_creation,
start_job,
wait_for_job,
**# TEARDOWN**
delete_app,
 delete_s3_bucket -> delete test branch if success

In the above dag, the airflow creates a lakeFS branch, launches an emr serverless instance and runs a potential Spark code on emr, waits for the job to finish, qualifies the results, and deletes the branch upon success.
This enables us to leverage lakeFS in a testing environment managed by airflow.

For this to work, we need to implement a delete operator independent of the lakeCTL solution currently provided with [BashOperator](https://docs.lakefs.io/integrations/airflow.html).

### PR DESCRIPTION
**Pull request by FredrikBakken**
Closes #53

Add new Airflow Operator `LakeFSDeleteBranchOperator` to delete branches by calling the LakeFS server.

Example:
1. Create a new branch on a LakeFS repo, e.g.: branch named `delete_me` on repo named `example`
2. Add the following to your Airflow DAG:
   ```python
   # new import
   from lakefs_provider.operators.delete_branch_operator import LakeFSDeleteBranchOperator

   # define delete branch task
   task_delete_branch = LakeFSDeleteBranchOperator(
        task_id="delete_branch",
        repo="example",
        branch="delete_me")
   ```
3. Run the DAG and check that the branch is now gone from the `example` repo

### CODE REVIEW

**Review by arielshaqed — COMMENTED** [review]
Hey, neat!

Can you please add it to the provider test?  This test has found a few bugs, and prevented _many_ regressions.

**Comment by FredrikBakken** [comment]
Not sure how you recommend adding it to the provider test? Is it the same as adding a new test like the [`tests/operators/test_create_symlink_operators.py`](https://github.com/treeverse/airflow-provider-lakeFS/blob/main/tests/operators/test_create_symlink_operators.py)?

**Comment by arielshaqed** [comment]
> Not sure how you recommend adding it to the provider test? Is it the same as adding a new test like the [`tests/operators/test_create_symlink_operators.py`](https://github.com/treeverse/airflow-provider-lakeFS/blob/main/tests/operators/test_create_symlink_operators.py)?

For most things on an Airflow provider we prefer an integration test.  This is run by .github/workflows/provider.yaml, that runs [lakefs_provider/example_dags/lakefs-dag.py](https://github.com/treeverse/airflow-provider-lakeFS/blob/main/lakefs_provider/example_dags/lakefs-dag.py).  That DAG can create a branch, delete it, and then see that it doesn't exist -- for instance by attempting to read from it before and after deletion, and seeing it succeeds the first time but fails the second.

**Comment by FredrikBakken** [comment]
@arielshaqed, provider test added to this branch delete operator feature.

**Review by arielshaqed — COMMENTED** [review]
Neat, thanks!

Passing tests then pulling.

**Review by arielshaqed — APPROVED** [review]
> Neat, thanks!
> 
> Passing tests then pulling.

I had _one_ job...

**Pull request merged**
